//DEFINICJA KONFIGURACJI CZERWONYCH GUZIKOW
//!!! PINY W NUMERACJI OFICJALNEJ, NIE WIRINGPI !!!//
#define PIN_DUZEGO_A 26//25
#define PIN_DUZEGO_B 19//24
#define PIN_DUZEGO_C 13//23
#define PIN_DUZEGO_D 6//22

#define PIN_DUZEGO_PRZELACZNIKA 5//21
#define PIN_MALEGO_PRZELACZNIKA 12//26