.\" Strona podręcznika dla programu eksportuj.
.\" Jak nie działa, to pisać na Discordzie, albo dzwonić.
.TH nagrywaj 1 "29 Marca 2023" "1.0" "System Monitorowania Aktywności Człowieka"
.SH NAZWA
eksportuj \- wypisz na standardowe wyjście tekstową reprezentację zapisu wyprodukowanego przez nagrywaj.
.SH STRESZCZENIE
eksportuj  [-c -h -e/-z -0] [plik wyjsciowy]
.SH OPIS
Program ten przetwarza binarny zapis z nagrywaj i produkuje jego reprezentacje tekstową (w csv). Zapisuje przy tym w pliku o tej samej nazwie, z dodanym przyrostkiem _pozycja, pozycje do której doszedł, więc jeżeli mu sie przerwie w trakcie, powinien zacząć od tego samego punktu, puszczony ponownie.
.SH OPCJE
.TP
.BR \-c \fR
Gdy dojdzie do konca pliku, czeka az pojawia sie kolejne dane
.TP
.BR \-h \fR
Format czytelniejszy dla ludzi, inaczej csv
.TP
.BR \-e \fR
Nie zapisuje pozycji do ktorej doszedl w pliku _pozycja i od razu zaczyna od konca pliku (uzyc z -c)
.TP
.BR \-z \fR
Zaczyna na poczatku pliku i wyklucza sie z -e


.SH ZOBACZ TEŻ
nagrywaj(1), kasuj(1), smaczdemon(1)
.SH BUGI
Jeszcze nas zjedzą.
.SH AUTOR
Mateusz Strzałkowski (strzamat@gmail.com)